# frozen_string_literal: true

require "test_helper"
require "tmpdir"
require "fileutils"
require "exhale/source_files"

class SourceFilesTest < Minitest::Test
  KEPT = {
    "app/models/user.rb" => "class User; end\n",
    "app/views/users/show.html.erb" => "<p>hi</p>\n",
    "app/views/users/show.turbo_stream.erb" => "<p>hi</p>\n",
    "lib/tasks/thing.rb" => "x = 1\n",
    "a.rb" => "a\n"
  }.freeze

  EXCLUDED = {
    "db/schema.rb" => "x\n",
    "config/routes.rb" => "x\n",
    "vendor/gem/a.rb" => "x\n",
    "node_modules/p/a.rb" => "x\n",
    "tmp/a.rb" => "x\n",
    "log/a.rb" => "x\n",
    "coverage/a.rb" => "x\n",
    "public/a.rb" => "x\n",
    "storage/a.rb" => "x\n",
    "bin/setup.rb" => "x\n",
    "app/assets/builds/a.rb" => "x\n",
    ".bundle/a.rb" => "x\n",
    "app/.hidden/a.rb" => "x\n",
    "app/models/readme.md" => "x\n",
    "app/cells/agent/prompt.erb" => "Summarize <url>\n",
    "app/views/users/show.json.erb" => "{}\n",
    "app/models/gen.rb" => "# frozen\n# Auto-generated by tool\nx\n",
    "app/models/gen2.rb" => "# DO NOT EDIT\nx\n",
    "app/models/bad.rb" => "x = \"\xFF\xFE\"\n".b
  }.freeze

  TESTS = {
    "test/models/user_test.rb" => "x\n",
    "spec/models/user_spec.rb" => "x\n",
    "app/spec/helper.rb" => "x\n",
    "lib/foo/test/helper.rb" => "x\n",
    "lib/foo_test.rb" => "x\n",
    "lib/foo_spec.rb" => "x\n"
  }.freeze

  def setup
    @root = Dir.mktmpdir("exhale-src")
    [KEPT, EXCLUDED, TESTS].each do |set|
      set.each do |path, content|
        full = File.join(@root, path)
        FileUtils.mkdir_p(File.dirname(full))
        File.binwrite(full, content)
      end
    end
  end

  def teardown
    FileUtils.remove_entry(@root)
  end

  def test_walks_and_excludes
    result = Exhale::SourceFiles.list(@root)
    assert_equal KEPT.keys.sort, result.map(&:first)
  end

  def test_languages
    result = Exhale::SourceFiles.list(@root).to_h
    assert_equal :ruby, result["app/models/user.rb"]
    assert_equal :erb, result["app/views/users/show.html.erb"]
    assert_equal :erb, result["app/views/users/show.turbo_stream.erb"]
  end

  def test_include_tests
    paths = Exhale::SourceFiles.list(@root, include_tests: true).map(&:first)
    assert_equal (KEPT.keys + TESTS.keys).sort, paths
  end

  def test_files_filter
    files = ["app/models/user.rb", "db/schema.rb", "app/models/readme.md", "zzz/missing.rb", "a.rb"]
    result = Exhale::SourceFiles.list(@root, files: files)
    assert_equal [["a.rb", :ruby], ["app/models/user.rb", :ruby]], result
  end

  def test_generated_header_only_in_first_five_lines
    File.write(File.join(@root, "late.rb"), "1\n2\n3\n4\n5\n# generated by x\n")
    assert_includes Exhale::SourceFiles.list(@root).map(&:first), "late.rb"
  end

  def test_unreadable_file_skipped
    path = File.join(@root, "locked.rb")
    File.write(path, "x\n")
    File.chmod(0o000, path)
    refute_includes Exhale::SourceFiles.list(@root).map(&:first), "locked.rb" unless Process.uid.zero?
  ensure
    File.chmod(0o644, path) if path && File.exist?(path)
  end
end
