# frozen_string_literal: true

require_relative "errors"

module Exhale
  # Lists the Ruby and ERB files exhale analyses.
  module SourceFiles
    EXCLUDED_ROOTS = %w[db config vendor node_modules tmp log coverage public storage bin].freeze
    EXCLUDED_PREFIXES = ["app/assets/builds/"].freeze
    GENERATED = /\b(auto-?generated|generated by|do not edit|don't edit)\b/i

    module_function

    def list(root, files: nil, include_tests: false)
      candidates = files ? files.map(&:to_s) : walk(root)
      candidates
        .select { |path| language(path) && path_allowed?(path, include_tests) }
        .sort
        .uniq
        .select { |path| readable_source?(File.join(root, path)) }
        .map { |path| [path, language(path)] }
    end

    def language(path)
      case path
      when /\.rb\z/ then :ruby
      # Herb reads HTML with ERB in it. Text, JSON and prompt templates that
      # happen to use ERB aren't HTML, so they aren't compared.
      when /\.html(\+[\w-]+)?\.erb\z/, /\.turbo_stream\.erb\z/ then :erb
      end
    end

    def walk(root)
      Dir.glob("**/*", base: root).select { |p| File.file?(File.join(root, p)) }
    end

    def path_allowed?(path, include_tests)
      segments = path.split("/")
      return false if segments.any? { |s| s.start_with?(".") }
      return false if EXCLUDED_ROOTS.include?(segments.first)
      return false if EXCLUDED_PREFIXES.any? { |p| path.start_with?(p) }

      include_tests || !test_path?(path, segments)
    end

    def test_path?(path, segments)
      segments[0..-2].any? { |s| %w[spec test].include?(s) } || path.end_with?("_spec.rb", "_test.rb")
    end

    def readable_source?(full)
      content = File.binread(full)
      content.force_encoding(Encoding::UTF_8)
      return false unless content.valid_encoding?

      content.each_line.first(5).none? { |line| line.match?(GENERATED) }
    rescue SystemCallError
      false
    end
  end
end
